export default {
    Ccar2012ACD: require("./images/2012 CCAR Assessment Coverage.jpg"),
    Ccar2012DataClassif : require("./images/2012 CCAR Data Classif.jpg"),
    Ccar2012EntityID: require("./images/2012 CCAR Entity ID.jpg"),
    Ccar2012FinCon: require("./images/2012 CCAR Financial Concept.jpg"),
    Ccar2012Metadata: require("./images/2012 CCAR Metadata.jpg"),
    Ccar2012Scenario: require("./images/2012 CCAR Scenario.jpg"),
    Ccar2012EQ: require("./images/2012 CCAR Exercise Quarter.jpg"),
    Dfast2012LoanACD: require("./images/2012 DFAST Loan Assessment Coverage.jpg"),
    Dfast2012LoanDataClassif: require("./images/2012 DFAST Loan Data Classif.jpg"),
    Dfast2012LoanEntityID: require("./images/2012 DFAST Loan Entity ID.jpg"),
    Dfast2012LoanFinCon: require("./images/2012 DFAST Loan Financial Concept.jpg"),
    Dfast2012LoanMetadata: require("./images/2012 DFAST Loan Metadata.jpg"),
    Dfast2012LoanScenario: require("./images/2012 DFAST Loan Scenario.jpg"),
    Dfast2012RevenueACD: require("./images/2012 DFAST Revenue Assessment Coverage.jpg"),
    Dfast2012RevenueDataClassif: require("./images/2012 DFAST Revenue Data Classif.jpg"),
    Dfast2012RevenueEntityID: require("./images/2012 DFAST Revenue Entity ID.jpg"),
    Dfast2012RevenueFinCon: require("./images/2012 DFAST Revenue Financial Concept.jpg"),
    Dfast2012RevenueMetadata: require("./images/2012 DFAST Revenue Metadata.jpg"),
    Dfast2012RevenueScenario: require("./images/2012 DFAST Revenue Scenario.jpg"),
    Dfast2021LoanACD: require("./images/2021 DFAST Loan Assessment Coverage.jpg"),
    Dfast2021LoanDataClassif: require("./images/2021 DFAST Loan Data Classif.jpg"),
    Dfast2021LoanEntityID: require("./images/2021 DFAST Loan Entity ID.jpg"),
    Dfast2021LoanEQ: require("./images/2021 DFAST Loan Exercise Quarter.jpg"),
    Dfast2021LoanFinCon: require("./images/2021 DFAST Loan Financial Concept.jpg"),
    Dfast2021LoanMetadata: require("./images/2021 DFAST Loan Metadata.jpg"),
    Dfast2021LoanScenario: require("./images/2021 DFAST Loan Scenario.jpg"),
    Dfast2021RatioACD: require("./images/2021 DFAST Ratio Assessment Coverage.jpg"),
    Dfast2021RatioDataClassif: require("./images/2021 DFAST Ratio Data Classif.jpg"),
    Dfast2021RatioEntityID: require("./images/2021 DFAST Ratio Entity ID.jpg"),
    Dfast2021RatioEQ: require("./images/2021 DFAST Ratio Exercise Quarter.jpg"),
    Dfast2021RatioFinCon: require("./images/2021 DFAST Ratio Financial Concept.jpg"),
    Dfast2021RatioMetadata: require("./images/2021 DFAST Ratio Metadata.jpg"),
    Dfast2021RatioScenario: require("./images/2021 DFAST Ratio Scenario.jpg"),
    Dfast2021RevenueACD: require("./images/2021 DFAST Revenue Assessment Coverage.jpg"),
    Dfast2021RevenueDataClassif: require("./images/2021 DFAST Revenue Data Classif.jpg"),
    Dfast2021RevenueEntityID: require("./images/2021 DFAST Revenue Entity ID.jpg"),
    Dfast2021RevenueEQ: require("./images/2021 DFAST Revenue Exercise Quarter.jpg"),
    Dfast2021RevenueFinCon: require("./images/2021 DFAST Revenue Financial Concept.jpg"),
    Dfast2021RevenueMetadata: require("./images/2021 DFAST Revenue Metadata.jpg"),
    Dfast2021RevenueScenario: require("./images/2021 DFAST Revenue Scenario.jpg"),
    Dfast2021RwaACD: require("./images/2021 DFAST RWA Assessment Coverage.jpg"),
    Dfast2021RwaDataClassif: require("./images/2021 DFAST RWA Data Classif.jpg"),
    Dfast2021RwaEntityID: require("./images/2021 DFAST RWA Entity ID.jpg"),
    Dfast2021RwaEQ: require("./images/2021 DFAST RWA Exercise Quarter.jpg"),
    Dfast2021RwaFinCon: require("./images/2021 DFAST RWA Financial Concept.jpg"),
    Dfast2021RwaMetadata: require("./images/2021 DFAST RWA Metadata.jpg"),
    Dfast2021RwaScenario: require("./images/2021 DFAST RWA Scenario.jpg")
}